groups:
  - name: basic alerts
    labels:
      team: infra
    rules:
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 10s #warning : should be 1m in real life
        labels:
          severity: critical
        annotations:
          summary: Prometheus target missing (instance {{ $labels.instance }})
          description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"