route:
  group_by: ['job', 'instance', 'alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: 'monitoring@octo.com'
        from: 'monitoring@octo.com'
        smarthost: 'mailpit:1025'
        require_tls: false
inhibit_rules: []
